# Generated by Django 5.0.3 on 2024-05-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
