# Generated by Django 5.0.3 on 2024-05-05 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_description_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='active_Listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='special_features',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_Url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
