# Generated by Django 5.0.3 on 2024-05-08 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_seller_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active_Listing',
            new_name='active_listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='image_Url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='seller_Notes',
            new_name='seller_notes',
        ),
        migrations.AddField(
            model_name='listing',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
