# Generated by Django 5.0.3 on 2024-05-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_active_listing_listing_active_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active_listing',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller_notes',
        ),
    ]
